# Generated by Django 5.0 on 2023-12-18 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400)),
                ("amount", models.CharField(max_length=200)),
                ("percent", models.CharField(max_length=200)),
                ("months", models.CharField(max_length=200)),
                ("percent_to_pay", models.CharField(max_length=200)),
                ("monthly_payment", models.CharField(max_length=200)),
                ("life_insurance", models.CharField(max_length=200)),
                ("payments_insurance", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
