# Generated by Django 5.0 on 2023-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="date",
            field=models.DateField(default="2023-12-18"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loan",
            name="time",
            field=models.TimeField(default="23:00"),
            preserve_default=False,
        ),
    ]
