# Generated by Django 4.2 on 2023-12-20 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_loan_date_loan_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paid_amount", models.CharField(max_length=100)),
                ("initial_paid", models.CharField(max_length=100)),
                ("percent_paid", models.CharField(max_length=100)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finance.loan"
                    ),
                ),
            ],
        ),
    ]
