# Generated by Django 4.2 on 2023-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_paymenthistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="life_insurance",
            field=models.CharField(default="0", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payments_insurance",
            field=models.CharField(default="0", max_length=100),
            preserve_default=False,
        ),
    ]
