# Generated by Django 4.2 on 2023-12-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_paymenthistory_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenthistory",
            name="time",
        ),
    ]
