# Generated by Django 4.2 on 2023-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_remove_paymenthistory_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="paid_date",
            field=models.DateField(default="2023-12-21"),
            preserve_default=False,
        ),
    ]
