# Generated by Django 4.2.6 on 2023-12-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymenthistory_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='name',
            field=models.CharField(default='name', max_length=400),
            preserve_default=False,
        ),
    ]
