# Generated by Django 4.2.6 on 2023-12-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_paymenthistory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='loan_name',
            field=models.CharField(default='saxeli', max_length=400),
            preserve_default=False,
        ),
    ]
