# Generated by Django 4.2.7 on 2023-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
